---
version: 2
plan:
  project-key: MARS
  key: ROCKET
  name: Build petclinic
stages:
- Default Stage:
    manual: false
    final: false
    jobs:
    - Job1
Job1:
  key: JOB1
  tasks:
  - clean
# Task com.atlassian.bamboo.plugins.maven:task.builder.mvn3 is not supported yet
  - script:
      interpreter: BINSH_OR_CMDEXE
      scripts:
      - /usr/local/src/apache-maven/bin/mvn clean install
     # - curl -v -u admin:admin123 --upload-file ${bamboo.path}/petclinic.war http://18.236.232.129:8081/nexus/content/repositories/Bamboo/${bamboo.buildNumber}/petclinic.war
# Task com.atlassian.bamboo.plugins.tomcat.bamboo-tomcat-plugin:deployAppTask is not supported yet
variables:
  path: /var/atlassian/application/bamboo/xml-data/build-dir/360449/MARS-ROCKET-JOB1/target
---
version: 2
# Short syntax
triggers:
  - polling: 10
