---
version: 2
plan:
  project-key: MARS
  key: ROCKET
  name: Build petclinic
stages:
  - Build war:
    - Build
    
Build:
  tasks:
    - clean
    - script:
      - echo 'Hello World!'
      - /usr/local/src/apache-maven/bin/mvn clean test
